import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";

import Navbar from "./components/navbar";
import Footer from "./components/footer";
import Header from "./components/header";
config.autoAddCss = false;
const inter = Inter({
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Suplements Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`{inter.className} {poppins.className}`}>
        <Navbar />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
